apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-mysql
  ports:
    - name: tcp
      protocol: TCP
      port: {{ .Values.mysql.port}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  replicas: 2
  serviceName: {{ .Release.Name }}-mysql
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Release.Name }}-mysql
          image: "{{ .Values.mysql.docker_image_repository }}:{{ .Values.mysql.docker_image_tag }}"
          ports:
            - name: tpc
              protocol: TCP
              containerPort: {{ .Values.mysql.port}}
          {{- if or .Values.secret_env .Values.env }} 
          envFrom:
          {{- if .Values.secret_env }} 
          - secretRef:
              name: {{ .Release.Name }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        {{- if .Values.mysqlresources }}
        resources:
         {{ toYaml .Values.mysqlresources | nindent 12 }}
        {{- end }}