{{- if .Values.service}}
{{- if .Values.service.type}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
{{- end }}
{{- end }}