env:  # to create configmaps which holds env values for app
  MYSQL_DATABASE: employees
secret_env: # will create secret in kubernetes for the app
  MYSQL_ROOT_PASSWORD: srilu #(pass values from key vault)

mysql:
  docker_image_repository: mysql # docker image for the mysql
  docker_image_tag: 5.7 # image tag
  replicaCount: 1 # number of replicas to run for an app
  port: 3306
  type: ClusterIP # type of service to be created for an app, by default it is ClusterIP
  volume:
    name: mysql-storage
    kind: PersistentVolumeClaim
    mountPath: /var/lib/mysql
    pvc:
      name: mysql-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 1Gi
