service:    # Required to create a deployment for the app
  docker_image_repository: srilakshmiattuluri/hsassessment # docker image for the app
  docker_image_tag: latest # image tag
  docker_image_pullPolicy: IfNotPresent 
  customStartUp: null # if need to excute a specific command on pod startup
  replicaCount: 2 # number of replicas to run for an app
  port: 4444
  type: NodePort # type of service to be created for an app, by default it is ClusterIP

healthcheck: # to enable liveness and readiness probes
  url: /healthz # route to check health of an app
  initialDelayinProbes: 30  
  timeout: 10
  failureThreshold: 5

env:  # to create configmaps which holds env values for app
  MYSQL_USER: root
  MYSQL_DATABASE: employees
secret_env: # will create secret in kubernetes for the app
  MYSQL_ROOT_PASSWORD: srilu #(pass values from key vault)

autoscaling: # to scale the pods automatically
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80 # condition for scaling for CPU
  targetMemoryUtilizationPercentage: 80 # condition for scaling for Memory

resources: # specify the resources required by an app on startup
  requests:
    cpu: 100m
    memory: 100Mi

mysql:
  docker_image_repository: mysql # docker image for the mysql
  docker_image_tag: 5.7 # image tag
  replicaCount: 2 # number of replicas to run for an app
  port: 3306
  type: ClusterIP # type of service to be created for an app, by default it is ClusterIP

mysqlresources: # specify the resources required by an app on startup
  requests:
    storage: 1Gi