{{- if .Values.secret_env}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
type: Opaque
data:
  {{- range $key, $val := .Values.secret_env }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
{{- end }}